# Description: This file is used to run the api tests in the docker container

networks: 
  mock:

services:

  mockin:
    image: hellocoop/mockin:latest
    networks:
      - mock
    ports:
      - '3333:3333'
      # debugger
      - '9339:9229'
    environment:
      ISSUER: 'http://mockin:3333'

  fastify-client:
    image: node:18-alpine
    depends_on:
      - mockin
    networks: 
      - mock
    working_dir: /usr/src/svr
    environment:
      HELLO_WALLET: 'http://mockin:3333'
      HELLO_COOKIE_SECRET: '66c71f55568f7b0c3b30cb6a8df9975b5125000caa775240b2e76eb96c43715e'
    volumes: 
      - type: bind
        source: ../
        target: /usr/src/svr  
      - type: bind 
        source: ../../node_modules
        target: /usr/src/node_modules
    ports:
      - "9229:9229"
    command: ["npm", "run", "spec"] 
 